# Build Maverick on python 3.5+

name: Build Py36

on:
  push:
    branches:
      - master

jobs:

  build_py35:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Build
      run: |
        python3 mvrk.py --config demo_src/config.py --source_dir ./demo_src/ --build_dir ./build_py36/
