# Build demo site and update gh-pages branch

name: Build demo

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.14
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.14

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Build
      env:
        site_prefix: /
      run: |
        python3 mvrk.py --config demo_src/config.py --source_dir ./demo_src/ --build_dir ./dist/

    - name: Deploy to GitHub Pages
      uses: docker://peaceiris/gh-pages:v2
      with :
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist
        emptyCommits: false
